--- #directories
  - :path: /etc/automated_brake/to_encode
    :out_path: /etc/automated_brake/encoded
    :delete: true
    :final_extension: m4v
    :options: -e x264 -b 2000 --pfr  -a 1,1 -E faac,copy:ac3 -B 160,160 -6 dpl2,auto -R Auto,Auto -D 0.0,0.0 -f mp4 --height 480 --loose-anamorphic -m --decomb
